### ISSUE TITLE
snore SIGSEGVs with long times

### ISSUE THREAD

**Issue by paride** [clamiax/snore#4]
For example:

```
$ ./snore 26000d
fish: “./snore 26000d” terminated by signal SIGSEGV (Address boundary error)
```

I know the time is not very reasonable, but `sleep` handles it fine, and SIGSEGVs are never nice.

**Comment by bitsmanent** [comment]
I bound the upper limit to UINT_MAX (962f4eded6effdc8474928ec02e3ca9e33ed753f). This works but let's see if there are better solutions.
